obstacle_range: 10.0
raytrace_range: 52.0
inflation_radius: 1.0
cost_scaling_factor: 1.0
transform_tolerance: 2.0
#footprint: [[-0.3, -1.0], [-0.3, 1.0], [1.8, 1.0], [1.8, -1.0]]
footprint: [[-0.3, -0.6], [-0.3, 0.6], [1.8, 0.5], [1.8, -0.5]]

static_layer:
  lethal_cost_threshold: 50
