local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 0.1
  publish_frequency: 0.1
  static_map: true
  rolling_window: true
  transform_tolerance: 2.0
  width: 10.0
  height: 10.0
  resolution: 0.05

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}

