local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 0.1
  publish_frequency: 0.1
  transform_tolerance: 2.0
  static_map: true
  width: 10.0
  height: 10.0
  resolution: 0.05

