obstacle_range: 10.0
raytrace_range: 52.0
transform_tolerance: 2.0
footprint: [[-1.9, -0.6], [-1.9, 0.6], [1.0, 0.5], [1.0, -0.5]]

static_layer:
  enabled: true
  lethal_cost_threshold: 50

inflation_layer:
  inflation_radius: 1.4
  cost_scaling_factor: 1.0

obstacle_layer:
    enabled: true
    observation_sources: livox
    
    livox: {
            sensor_frame: livox_frame,
            data_type: PointCloud2,
            topic: points2,
            marking: true,
            clearing: true,
            min_obstacle_height: -1.6,
            max_obstacle_height: 1.2
           }
