local_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 2.0
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05

  obstacle_layer:
    observation_sources: laser_scan_sensor

    laser_scan_sensor: {
      sensor_frame: laser,
      data_type: LaserScan,
      topic: /fake_scan,
      marking: true,
      clearing: true
    }
