image: ../data/utum_map_LIVOX.pgm
resolution: 0.050000
# ToDo: origin needs to be updated!
origin: [-25.019196, -20.317178, 0.0]
negate: 0
# we might need to tune the thresholds!
occupied_thresh: 0.65
free_thresh: 0.196
